services:
  frontend:
    image: flask-api:01
    pull_policy: never
    links:
      - "backend:database"
    ports:
      - "127.0.0.1:5000:5000/tcp"
    environment:
      DB_USER: "root"
      DB_PASSWORD: "Test123"
      DB_HOST: "database"
      DB_PORT: 3306
      DB_AUTOCOMMIT: "False"
      DB_DATABASE: "MovieGuru"
      DB_TS_ISOLATION_LEVEL: "SERIALIZABLE"
  backend:
    image: mysqlserver:01
    pull_policy: never
    ports:
      - "127.0.0.1:30060:30060/tcp"
    environment:
      MYSQL_ROOT_PASSWORD: "Test123"
    volumes: 
     - source: app-data/
       type: bind
       target: /var/lib/mysql
